<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.1 lock.glb --transform
-->

<script lang="ts">
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf, useGltfAnimations } from "@threlte/extras";

  export const ref = new Group();
  export let color: string;

  const gltf = useGltf("/models/lock-transformed.glb", { useDraco: true });
  export const { actions, mixer } = useGltfAnimations(gltf, ref);

  const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <!-- <T.Mesh
        name="Cube"
        geometry={gltf.nodes.Cube.geometry}
        material={gltf.materials.Material}
        scale={[0.53, 1.78, 1.78]}
      />
      <T.Mesh
        name="Text"
        geometry={gltf.nodes.Text.geometry}
        material={gltf.materials["Material.001"]}
        position={[0.01, 3.22, -1.37]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.78, 1, 2.99]}
      /> -->
      <T.Mesh
        name="Cube"
        geometry={gltf.nodes.Cube.geometry}
        scale={[0.53, 1.78, 1.78]}
      >
        <T.MeshStandardMaterial {color} />
      </T.Mesh>
      <T.Mesh
        name="Text"
        geometry={gltf.nodes.Text.geometry}
        position={[0.01, 3.22, -1.37]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={[3.78, 1, 2.99]}
        {color}
      >
        <T.MeshStandardMaterial {color} />
      </T.Mesh>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
